package com.app.guardian.common

class ConstantCodes {
    enum class EmailValidationResult(val result: Int) {
        EMAIL_VALID(0), USERNAME(1), MOBILENUMBER(2), EMAIL_FAILED(3), PASSWORD_FAILED(4), PASSWORD_VALID(5), CONFIRM_PASSWORD(6), CONFIRM_PASSWORD_FAILED(7), USERNAME_FAILED(8), OTP_VALID(9), MOBILENUMBER_VALID(10), BANK_ACC_NUMBER(11), BANK_ACC_NUMBER_VALID(12), BANK_ACC_NUMBER_FAILED(13), CONFIRM_BANK_ACC_NUMBER(14), CONFIRM_BANK_ACC_NUMBER_FAILED(15), BANK_ACC_TYPE(16), BANK_ACC_TYPE_VALID(17), BANK_ACC_TYPE_FAILED(18), BANK_ACC_SORT_CODE(19), BANK_ACC_SORT_CODE_VALID(20), BANK_ACC_SORT_CODE_FAILED(21), BANK_NAME(22), BANK_NAME_VALID(23), BANK_NAME_FAILED(24), CARD_NUMBER(25), CARD_NUMBER_FAILED(26), MONTH_INVALID(27), YEAR_INVALID(28), CVV_INVALID(29);

    }
}