package com.app.guardian.model.LawyerProfileDetails

data class LawyerProfileDetailsResp(
    val created_at: String?="",
    val plan_id:Int,
    val deleted_at: String?="",
    val email: String?="",
    val fp_status: String?="",
    val full_name: String?="",
    val id: Int?=0,
    val licence_no: String?="",
    val changephone_otp :String?="",
    val office_phone: String?="",
    val phone: String?="",
    val plan_expiry_date: String?="",
    val postal_code: String?="",
    val profile_avatar: String?="",
    val last_seen: String?="",
    val specialization: String?="",
    val state: String?="",
    val status: String?="",
    val updated_at: String?="",
    val user_role: String?="",
    val vehicle_no: String?="",
    val years_of_experience: String?="",
    val description: String?="",
    val is_subscribe: Int?=0,
    val firebase_uid: String?="",
    val firebase_chatid: Int?=0,
    val dialing_code: String?="",
    val office_dialing_code: String?="",
    val availability_time: String?="",
)
