package com.app.guardian.utils


class ApiConstant{
    companion object{
     val EXTRAS_EMAIL="email"
     val EXTRAS_PHONE="phone"
     val EXTRAS_PASSWORD="password"
     val EXTRAS_DEVICETOKEN="device_token"
     val EXTRAS_PRICE_ID="pricing_id"
     val EXTRAS_APPLE_RECEIPT="apple_receipt"
     val EXTRAS_SHARED_SECRET="shared_secret"
     val EXTRAS_START_DATE="start_date"
     val EXTRAS_END_DATE="end_date"
     val EXTRAS_PRICE="price"
     val EXTRAS_SOCIAL_ID="social_id"
     val EXTRAS_LOGIN_TYPE="login_type"
     val EXTRAS_OTP="otp"
     val EXTRAS_NEW_PASS="new_password"
     val EXTRAS_CONFIRM_PASS="confirm_password"
     val EXTRAS_FULL_NAME="fullname"
     val EXTRAS_FULL_UNDERSCORE_NAME="full_name"
     val EXTRAS_STATE="state"
     val EXTRAS_PROFILE_AVATAR="profile_avatar"
     val EXTRAS_USER_DOC="user_doc"
     val EXTRAS_USER_ID="user_id"


     val EXTRAS_REFERAL_CODE="referral_by"
     val EXTRAS_MEMBER_FULL_NAME="member_fullname"
     val EXTRAS_PROFILE_IMAGE="profile_image"
     val EXTRAS_MEMBER_EMIAL="member_email"
     val EXTRAS_PRIVACY_POLICY="accept_policy"
     val EXTRAS_USER_LAT="user_lat"
     val EXTRAS_USER_LONG="user_long"
     val EXTRAS_PAYMENT_CARD_NUMBER="card_number"
     val EXTRAS_PAYMENT_CARD_EXP_MONTH="exp_month"
     val EXTRAS_PAYMENT_CARD_EXP_YEAR="exp_year"
     val EXTRAS_PAYMENT_CARD_CVV="cvv"
     val EXTRAS_PAYMENT_CARD_HOLDER_NAME="holder_name"
     val EXTRAS_PAYMENT_CARD_ID="card_id"
     val EXTRAS_PAYMENT_CART_ID="cart_id"
     val EXTRAS_FILTER_SORT_BY="sort_by"
     val EXTRAS_FILTER_RATTING="rating"
     val EXTRAS_FILTER_CURENT_PAGE="current_page"
     val EXTRAS_USER_BUSINESS_TYPE="business_type"
     val EXTRAS_USER_PROPERTY_TYPE="property_type"
     val EXTRAS_NAME="name"
     val EXTRAS_SEARCH="search"
     val EXTRAS_LOCATION="location"
     val EXTRAS_HOUSE_NO="house_no"
     val EXTRAS_NO_OF_BEDROOMS="no_of_bedrooms"
     val EXTRAS_ABOUT_ROOMS="about_room"
     val EXTRAS_PROPERTY_TYPE_ID="property_type_id"
     val EXTRAS_AMENITIES="amenities"
     val EXTRAS_AVAILABILITY="availability"
     val EXTRAS_CHECK_IN="check_in"
     val EXTRAS_CHECK_OUT="check_out"
     val EXTRAS_DESC="description"
     val EXTRAS_HOUSE_RULES="house_rule"
     val EXTRAS_HEALTH_SAFETY="health_safety"
     val EXTRAS_LAT="lat"
     val EXTRAS_LONG="long"
     val EXTRAS_PER_MONTH_FEE="per_month_fee"
     val EXTRAS_IMAGES="images[]"
     val EXTRAS_ACCOMODATION_ID="accommodation_id"
     val EXTRAS_RENTAL_ID="rental_id"
     val EXTRAS_PROPERTY_ID="property_id"
     val EXTRAS_DELETE_IMG_ID="delete_images_id"
     val EXTRAS_ADDRESS="address"
     val EXTRAS_CITY="city"
     val EXTRAS_COUNTRY="country"
     val EXTRAS_POSTAL_CODE="postal_code"
     val EXTRAS_DOB="date_of_birth"
     val EXTRAS_CULTURAL_BACK="cultural_background"
     val EXTRAS_MATERIAL_STATUS="material_status"
     val EXTRAS_LENGTH_STAY="length_of_stay"
     val EXTRAS_SOURCE_INCOME="sorce_of_income"
     val EXTRAS_RENTAL_REASON="rental_reason"
     val EXTRAS_JOB_ID="job_id"
     val EXTRAS_JOB_TYPE="job_type"
     val EXTRAS_BUSINESS_ID="business_id"
     val EXTRAS_RENTER_ID="renter_id"
     val EXTRAS_BUSINESS_USER_ID="business_user_id"
     val EXTRAS_BUSINESS_CATEGORY_ID="business_category_id"
     val EXTRAS_FAVOURITE_ID="favorite_id"
     val EXTRAS_ORDER_ID="order_id"
     val EXTRAS_PRODUCT_ID="product_id"
     val EXTRAS_ITEM_RATE="item_rate"
     val EXTRAS_REST_RATE="restaurant_rate"
     val EXTRAS_FAVOURITE_STATUS="favorite_status"
     val EXTRAS_ITEM_TYPE="item_type"
     val EXTRAS_ITEM_ID="item_id"
     val EXTRAS_ITEM_QUENTITY="item_quantity"

     val EXTRAS_REVIEWS="review"
     val EXTRAS_ITEM_SUB_TOTAL ="sub_total"
     val EXTRAS_ITEM_DISCOUNT ="discount"
     val EXTRAS_ITEM_GRAND_TOTAL ="grand_total"
     val EXTRAS_ITEM_BUY_FOR ="buy_for"
     val EXTRAS_ITEM_FULL_NAME ="full_name"

     val EXTRAS_ITEM_REWARD_BAL_USE ="reward_balance_use"
     val EXTRAS_IS_RESERVED ="is_reserved"
     val EXTRAS_MEAL_QTY_DISCOUNT ="meal_quantity_discount"
     val EXTRAS_DRINK_TOKEN_DISCOUNT ="drink_token_discount"
     val EXTRAS_MEMBERSHIP_DISCOUNT_PER ="membership_discount_percentage"
     val EXTRAS_MEAL_QTY_DISCOUNT_PER ="meal_quantity_discount_percentage"
     val EXTRAS_DRINK_QTY_DISCOUNT_PER ="drink_quantity_discount_percentage"
     val EXTRAS_CATEGORY_ID ="category_id"
     val EXTRAS_OLD_PASS ="old_password"
     val EXTRAS_PASSWORD_CONFIRMATION ="password_confirmation"
     val EXTRAS_IS_MEMEBRS ="is_member"
     val EXTRAS_STATUS ="status"


    }
}